### ISSUE TITLE
User Interface - Self-Serve Portal - Software Installation Page

### ISSUE THREAD

**Issue by nsheikh12** [nsheikh12/PRJ666NAA_Group09#10]
### User Story
As a user I want to provide information regarding my device to the IT department so that they can know what hardware and software specifications my computer has so that they can help me solve my problem in a faster and efficient way. I also want to know what software I should have downloaded on my device to give remote access to the IT department before being contacted by the IT department. 

### Description
A series of short questions will be asked to the user and the user will be given text input fields and radio buttons to answer those questions regarding their device. The user will have the option to go to the next screen only once they have answered the current question. The user can also go to a previous question if they need to change any answer. Once the user has finished answering the questions, they will be given a download link to install remote assistance software if they want to give the IT department access to their device for fixing a specific issue. 

### Acceptance Criteria

- [ ] Users should be able to enter single-line text for the text input fields. 
- [ ] The "Next" button should only be available in all fields that are not empty. 
- [ ] Pressing the "Next" button should take the user to the next screen. 
- [ ] The radio button should only allow a single selection to be made. 

### Testing

- [ ] Make a single selection on the radio input option
- [ ] Try to make multiple selections on the radio input option
- [ ] Click the "Next" button when all fields are empty
- [ ] Click the "Next" button when one field is filled and all other fields are empty. 
- [ ] Enter long text in text input fields to make sure all text stays in one line.

**Comment by isabellaliu77** [comment]
Closed by #6861bb92639ac4709ee23edc36673407caa3da38

**Comment by isabellaliu77** [comment]
Closed by #https://github.com/nsheikh12/PRJ666NAA_Group09/commit/6861bb92639ac4709ee23edc36673407caa3da38
