### ISSUE TITLE
User Interface - Self-Serve Portal - Time/Shift Management Page

### ISSUE THREAD

**Issue by AMeleshchchenko** [nsheikh12/PRJ666NAA_Group09#13]
### User Story
As an admin user, I want to be able to go to a page and be able to view all of the schedule for all the employees for a period of time. I want to also be able to view the schedule for a specific employee. I also want to have the option to edit a schedule for a specific employee and have the option to add an existing employee to the schedule. 

### Description
The Time/Shift Management page should have a table which displays the days of the week as the headers, and item card inside each column. The item cards contain the name of the employee and the time the are working for the shift. The page also includes an option to select a week to display the schedule for. The page should also include buttons to edit the schedule, add an existing employee to the schedule, Save, and Cancel.  

### Acceptance Criteria

- [ ]  Table includes all days of the week as headings.
- [ ]  Page includes Edit, Add, Save, and Cancel buttons.
- [ ]  Item cards include employee name, and time duration for shift.
- [ ] Page includes select list to filter weeks.
- [ ] Page includes select list to filter schedule for a specific employee.
- [ ] Page includes a paging feature which allows to easily go to next and previous weeks. 
- [ ] Page includes week start and end dates. 

### Testing
For testing purposes, the developer will add some employees with their schedule to the page for a specific week. 

- [ ] Table with week days as headings is displayed.
- [ ] Dropdown list with "All employees" and specific employee names is display.
- [ ] Calendar to select week is displayed.
- [ ] Edit button and Add buttons are displayed. 
- [ ] Each employee card is displayed with employee name and shift timings. 
- [ ] Save and Cancel buttons are displayed.

**Comment by nsheikh12** [comment]
Feature is removed from project.
