### ISSUE TITLE
User Interface - Self-Serve Portal - Admin Management Page

### ISSUE THREAD

**Issue by AMeleshchchenko** [nsheikh12/PRJ666NAA_Group09#14]
### User Story
As an admin user, I want the admin dashboard page to include a features management option that allows me to manage the data on the back-end.

### Description
The Admin Management Page will include a list of all the features with a link to go to specific pages for the management of each function. The feature management page is only available to admin users. The page should include links for resetting passwords. 

### Acceptance Criteria

- [ ]  Page displayed all functions that need the admin users to manage.
- [ ]  Each feature contains a link to enter the specific page.
- [ ] Page includes "Reset Password" button.

### Testing
For testing purposes, the developer will try to click links to see if the links work. 

- [ ] Try the link below Device Inventory to see if it goes to a different page including details of device inventory. 
- [ ] Try to click the link below Articles List to see if it goes to another page including the article list.

**Comment by isabellaliu77** [comment]
Closed by #https://github.com/nsheikh12/PRJ666NAA_Group09/commit/6861bb92639ac4709ee23edc36673407caa3da38
