### ISSUE TITLE
Application Layout - Login Page

### ISSUE THREAD

**Issue by nsheikh12** [nsheikh12/PRJ666NAA_Group09#2]
### User Story
As a user I want the login form to be visually appealing and easily fillable in order to be authenticated into the application. I want the login form to have easily recognizable Username and Password fields, as well as the Log In button. I also want the password field to dot the text that I will be typing into the password field.

### Description
A form will be created for the Login page that will have the text, "Username". After the text, it will have an editable text field, that will have placeholder text such as, "Enter your Username". On the next line, below the "Username" text, another text will be included that says, "Password" and it will have a special password field that will turn the users' text into dots, the field will have a placeholder text such as, "Enter your Password". Lastly, below the "Password" text, there will be a big button with large text that will say, "Log In". This layout will be very easy for the user to understand what to put in each field, and where to press in order to be authenticated into the application. This form layout will be created using the React framework.

### Acceptance Criteria

- [x] Contains Username and Password fields
- [x] Contains a Log In button
- [x] Both the Username and Password fields have placeholder text in them
- [x] Both of the Username and Password fields are editable

### Testing
For testing, the developer of the Login page form will be the one testing the form:

- [x] Username field is editable
- [x] Password field is editable
- [x] both fields have placeholder text that once the field is clicked will be removed and the user can type in the field
- [x] The "Log In" button is clickable

**Comment by AMeleshchchenko** [comment]
The Log In page is complete with two fields for username and password, as well as, a "Log In" button

**Comment by AMeleshchchenko** [comment]
Issue Closed
