### ISSUE TITLE
Create API to fetch data from database

### ISSUE THREAD

**Issue by nsheikh12** [nsheikh12/PRJ666NAA_Group09#29]
### User Story
As a user/admin user, I should be able to fetch user information stored in the database, read current tickets, check current troubleshoot articles. To achieve this, we need an API to connect our program with the database to be able to fetch, read, update and put data to the database. 

### Description 
For the database, we have decided to use the MongoDB Atlas cloud storage database. We will be registering on MongoDB Atlas and create a cluster for our project on it, and inject sample data. Then we will be creating the API to connect with it for the data manipulation later on. The API should be able to fetch data from it. 

### Acceptance Criteria
The API should be able to perform Create, Read, Update, and Delete functionalities.

### Testing
For testing purposes, These below parts will be focused to test that the CRUD functionalities of the API are working as expected:

- [x] Create new objects
- [x] Read existing
- [x] Update existing
- [x] Delete existing

**Comment by isabellaliu77** [comment]
The issue is completed.
