### ISSUE TITLE
User Login

### ISSUE THREAD

**Issue by nsheikh12** [nsheikh12/PRJ666NAA_Group09#37]
### User Story
As a user, I need the Login page to allow me to enter my username and password to get access to the resources that are only visible to registered users. 

### Description
There are two types of users: regular users, and admin users. A regular user can log in and fill in issue forms and service request forms. An admin user can get access to the ticketing system, which includes all manipulations of the tickets. When logged in, cookies should be saved in the browser for one hour without logging out. 

### Acceptance
If a user enters correct account information, the page will be redirected to the home page or management dashboard page(admin user). If wrong information is entered, an error message should be displayed below the login form. 

### Testing
For testing purposes, the below parts should be implemented and function as expected: 
- [x] Correct users can log in successfully
- [x] Wrong information cannot be logged in and an error message will be displayed on the page
- [x] Regular users will be redirected to the home page after logging in
- [x] Admin user will be redirected to management console after logging in.

**Comment by isabellaliu77** [comment]
Closed by #12e8ef5aefd692c45ef078fed1005933b2262edc
