### ISSUE TITLE
FAQ browsing feature

### ISSUE THREAD

**Issue by nsheikh12** [nsheikh12/PRJ666NAA_Group09#39]
### User Story
FAQ is a very important part of a self-service system. A properly designed FAQ section can help to reduce the time that a customer service agent is being occupied by a simple common issue and make the agent ready for the problem that really needs time to investigate. As the normal component, regular users want to view the FAQ articles in an efficient way. For admin users, they want to easily create a new article, delete or modify an existing article.

### Description
The FAQ needs to be present in a folding format. i.e. Only the title can be showing up initially. The body of an FAQ article can be shown up only by the user clicking the title. To avoid distracting users, only the FAQ articles that the users are reading are displayed. The editing function needs to allow admin users to change the category, title, and body of an FAQ article. The delete function is to lets the user delete any existing articles. Supporting group delete is optional. Once the user deletes/updates an article, it should be disappeared/be updated immediately without any manual refresh.

### Testing

- [x] Browsing--All articles should be retrieved from the database
- [x] Browsing--All articles should be 'closed' or 'folded-up initially until the user clicks the title to open. OR only the first article may open/unfold, other FAQ articles should remain closed.
- [x] Browsing--Once the user clicks on another article, the previous opened article should be folded up and closed automatically. i.e. only one article may open at a time.
- [x] Creation -- All parts should be manually entered (Title, body, and category)
- [x] Creation -- After filling the form, automatically switch to the FAQ browsing page.
- [x] Editing -- All previous content should be showing up and editable.
- [x] Editing -- After submitting a change to any previous content, jump back to the FAQ browsing page and the article should be updated.
- [x] Deleting -- After clicking on the button, the article should be deleted immediately and reflected on the FAQ browisng page without manually refreshing.

**Comment by dmao6** [comment]
All required test(s) are passed. Issue closed.
