### ISSUE TITLE
Application Layout - Management Console

### ISSUE THREAD

**Issue by nsheikh12** [nsheikh12/PRJ666NAA_Group09#4]
### User Story
As an admin user, I want the layout of the management console to be visually appealing and easy to navigate and use in order to add, edit and remove features from the Self-Serve Portal.

### Description
The Management Console should provide navigations of the Self-Serve Portal, and there will be functions of adding, editing and removing features from the Self-Serve Portal. 

### Acceptance Criteria

- [x] There should be a menu of features. 
- [x] There should be "add, edit, remove" buttons to perform corresponding functions. 
- [x] There should be "save, submit" buttons.

### Testing
For testing purposes, an admin user will be added to the database. Then, the admin user will test:

- [x] features can be viewed through the management console.
- [x] buttons to add, edit and remove features can be seen on the page.
- [x] buttons to save and submit settings of the features can be seen on the page.

**Comment by isabellaliu77** [comment]
3abd6a684f69e77518cdf5992d3a4c2d68d6de7a closes #4
