### ISSUE TITLE
Software Download Feature

### ISSUE THREAD

**Issue by nsheikh12** [nsheikh12/PRJ666NAA_Group09#42]
### User Story
As a user/visitor, I should be able to get different instructions regarding software downloading based on different choices of the operating systems. 

### Description
There is an options list showing choices of operating systems, users can select the one they are using for instruction of software downloading. 

### Acceptance
The user can only select one option, and the specific instruction should show only when the "next" button is pressed, and the content would change if the user reselects the option and press the button. 

### Testing
For testing purposes, the below parts should be implemented and function as expected: 
- [x] Only one option can be selected
- [x] The button can be pressed and only after it is pressed, the instruction would show
- [x] The instruction content would change when the option is changed.

**Comment by isabellaliu77** [comment]
Closed by 12e8ef5
