### ISSUE TITLE
Create ticket feature

### ISSUE THREAD

**Issue by nsheikh12** [nsheikh12/PRJ666NAA_Group09#43]
### User Story
As a user of the ticketing system, I want to be able to successfully submit a ticket based on user information and have it saved to the database.

### Description
For this task, the already made database API hosted on Heroku will be used to save ticket data to the MongoDB database.

### Acceptance Criteria
Should be able to successfully submit a ticket and have it save to the database.

### Testing

- [x] Table will display Ticket data dynamically
- [x]  When a ticket is created, it will be automatically displayed in the table
- [x]  Delete button will delete the ticket

**Comment by isabellaliu77** [comment]
closed by #61
