### ISSUE TITLE
Email-ticket conversion feature

### ISSUE THREAD

**Issue by nsheikh12** [nsheikh12/PRJ666NAA_Group09#44]

**Comment by dmao6** [comment]
### User Story
As a user that looking for technical support, I want to have multiple ways to contact the supporting person. Not always call them on the phone, sometimes I prefer to write an email. I hope my email can be picked by the service agent as soon as possible and my issue will be addressed soon. 

### Description
For this task, the user should be able to send an email to a designated email address and once the system detected a new email camming in, the new email should be parsed and the information should be extracted. Then a new ticket will be created and the extracted information should be automatically filled in If the email cannot be extracted, the entire email body should be attached as a ticket description.

### Acceptance Criteria
After the email has been sent to a designated email address, a new ticket should be automatically generated with necessary information OR the body of the email should be attached in the ticket description.

### Testing
1. Send an email to the designated email address
2. New ticket created automatically
3. The new ticket should have necessary information.

**Comment by dmao6** [comment]
New email detected and the ticket created.
