### ISSUE TITLE
Ticket transfer/escalate feature

### ISSUE THREAD

**Issue by nsheikh12** [nsheikh12/PRJ666NAA_Group09#45]

**Comment by dmao6** [comment]
### User Story
As a user of the ticketing system, sometime the ticket is out of my responsibility or I need additional authorization. In this case I need to let my supervisor or the senior level techicians knows my situation. To keep the content information as is, I need a function that can make them pay attention.

### Description
The ticket transferring system is mainly to bring the other staffs attention. Therefore, an email should be automatically sent to the receipient. If the receipient replies the email, the content of that reply email should be logged. The receipient should be able to maintained

### Acceptance Criteria
Once the user choose to escalate the ticket, they need to fill and submit a form. Then the receipient should receive an email with the content of the ticket itself and the the content on the form. The receipeint should be able to directly reply the email and the content replied should be logged and showing in the History section.

### Testing

- [ ]  1. Filling and submit the form
- [ ]  2. Expecting a email from designated receipient account, the email should including the content of the ticket itself with all necessary information and the information in the form
- [ ]  3. When the user reply the email. The replied email should be parsed and logged.
- [ ]  4. Optional feature: The receipient should be able to know the email of the person who submit the ticket. When make a reply, the receipient should get an update as well.
