### ISSUE TITLE
Ticket history logging 

### ISSUE THREAD

**Issue by nsheikh12** [nsheikh12/PRJ666NAA_Group09#47]
**User Story**
As a user of the ticketing system, I want to be able to see a log of all of the tickets that have been closed in the system, by myself, as well as, by all of the other users that closed their tickets.

**Description**
For this task, in the ticketing system, the user who is logged into the ticketing system, will be able to view a log of all of the tickets that have been closed.

**Acceptance Criteria**
The user must be able to view the log of all the tickets that have been closed by both the user themselves, as well as, other users who have been able to close their tickets.

**Testing**

- [x] Closed tickets that were closed by the user are displayed
- [x] Closed tickets that were closed by other users are displayed

**Comment by AMeleshchchenko** [comment]
All testing has been completed successfully
