### ISSUE TITLE
Show all tickets dynamically in List Ticket

### ISSUE THREAD

**Issue by nsheikh12** [nsheikh12/PRJ666NAA_Group09#57]
**User Story**
As a user of the ticketing system, I want to have a dynamic table that will display me all of the tickets that are currently stored in the Ticket database, as well as, I want o have a "Delete" button that will delete the ticket from the table

**Description**
For this task, I will need to make the table fetch data from the "Ticket" API and display information about each ticket in each row of the table. Each row will also need to have a red "Delete" button that once pressed will delete the row.

**Acceptance Criteria**
Table is able to dynamically display tickets and "Delete" button will delete the row once clicked

**Testing**

- [x]  Table will display Ticket data dynamically
- [x] When a ticket is created, it will be automatically displayed in the table
- [x]  Delete button will delete the ticket

**Comment by AMeleshchchenko** [comment]
Testing successfully completed. Issue Closed
