### ISSUE TITLE
Modified existing ticket (Add comment only)

### ISSUE THREAD

**Issue by nsheikh12** [nsheikh12/PRJ666NAA_Group09#58]
### User Story
As a user of the ticketing system, I want to be able to update a ticket comment. I want to be able to enter a ticket number I want to update and enter a comment for the ticket. 

### Description
For this task, the user will enter the ticket ID to search for the ticket, and once found, the ticket information form will be shown and the comment can be modified by the user. After the user enters comments and clicks the update button below the form, the newly added comment will be saved. 

### Acceptance Criteria
If a ticket number is not found, an error message should be displayed. If a valid ticket number is provided, it should redirect the user to the ticket information form after clicking the button "log". When new comments are added, the user should be able to save them by pressing the button "update" below the form.

### Testing
- [x]  Try modifying a ticket (valid ticket number)
- [x]  Try entering an invalid ticket ID (no results should be shown), an error message will be shown
- [x]  Try if other information other than comment can be modified.

**Comment by isabellaliu77** [comment]
Closed by #69
