### ISSUE TITLE
Combine report issue and create new issue API and UI

### ISSUE THREAD

**Issue by nsheikh12** [nsheikh12/PRJ666NAA_Group09#65]

**Comment by dmao6** [comment]
### User Story
As a user of the ticketing system, I want to be able to filter through the tickets that have been submitted through by both the user and an IT agent. Once I submitted an issue there, a new ticket should be created as well.

### Description
For this task, once the user submits a issue use issue form, a new ticket should be automatically created with the information that the user provided in the issue form.

### Acceptance Criteria
Searching a ticket successfully updates the table to display the entered ticket number or, no ticket found if nothing was found. Running a filter updates the table to successfully only show tickets that meet the criteria.

### Testing
 1. Submitted an issue use the report issue form
 2. Checke a new ticket should be displayed in the list, with all necessary information

**Comment by dmao6** [comment]
Now all other information can be transferred but the attached file cannot.
I am working on that

**Comment by isabellaliu77** [comment]
Closed by dccfe413d152b92e1b7cb516645f8fd9b151ef14.
