### ISSUE TITLE
User Interface - Self-Serve Portal - Device Rental Page

### ISSUE THREAD

**Issue by nsheikh12** [nsheikh12/PRJ666NAA_Group09#8]
### User Story
As a user I want to Device Rental page to be easily accessible, have up-to-date information about which equipment is currently available for renting and the location for the specific device. I want each device to have a proper image or icon associated with the name so it is easily identifiable. I want the device rental form to be easy to fill.

### Description
An authenticated user will be able to submit a form for device rental in order to get approved for picking up a device from a specific location. A table needs to show up-to-date information regarding the name of the equipment, amount of each equipment currently available for rental, as well as an icon or image to show what the device is. A form will be provided to the user which includes text input fields for their full name, student ID, select lists for equipment type, program duration, program name, and current home campus. The page will also include buttons to submit or cancel the rental request. 

### Acceptance Criteria
User should be able to view a table which includes device name, current available quantity, and an icon/image. Users should be able to enter their full name into the "Requesting Person" text input field, their student ID in the "Student ID" field, be able to make a single selection from the select list for "Equipment", "Duration", "Program", and "Campus". 

### Testing
For testing purposes, a few devices would be added to the table, and a few options would be added to the select lists. Then the following would be attempted:

- [x] Entering text into the name and ID fields.
- [x] Selecting a single item from the "Equipment", "Duration", "Program", and "Campus" lists. 
- [x] Attempting to select multiple options from the "Equipment", "Duration", "Program", and "Campus" lists. 
- [x] Able to view multiple entries in the device rental table with an icon/image for each. 
- [x] Submit and Cancel Buttons are visible at the bottom of the page.

**Comment by AMeleshchchenko** [comment]
Added UI and tested for the Device Rental Page in the portal
